<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQO3gDRM\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQO3gDRM/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQO3gDRM.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQO3gDRM\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerQO3gDRM\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'QO3gDRM',
    'container.build_id' => 'b0c15954',
    'container.build_time' => 1532507219,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerQO3gDRM');
